Create seed file with survey-sourced responses
caristopmer/whats-next-api pull request #6
Opened 2017-07-29 22:15 UTC by BB8bear

2017-07-29 22:31 UTC, kvrag submitted a review, later dismissed

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Work out.",
I would change line 51 to "Jog around the block, or longer if you're up for it."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Go for a run.",
Delete line 54

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Medidate.",
Line 57 - misspelled "meditate"

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Go for a walk.",
Delete line 58 (repeat)

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Go outside.",
Change line 60 to "Go outside or open a window for some fresh air."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Take a moment to be present in the moment.",
Change line 68 to "Take a moment to center yourself with deep breaths. Clear your mind."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Take a time out.",
Delete line 70 - kinda vague

Add -   "Do 10 pushups. Do another 10 if it feels good.",
  "Yell into a pillow."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Seek out support.",
Delete line 84 - same as 81 ish

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Exercise.",
Delete line 88 - we have lots of exercise ones

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Change your surroundings.",
Change line 90 to "Change your surroundings, if you can."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Mow your lawn."
Delete lines 96, 100, 103, 104 -- add   "Take a moment to feel gratitude for all that you have!",
  "Journal about this moment.",
  "Treat yourself with something you've wanted for a while."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Spend some time to take care of an easy task."
Edit line 119 - "Take care of an easy task or small chore, like emptying the dishwasher."

Add -   "Cry, if you want to.",
  "Call or text someone you're close to.",
  "Have you eaten recently? Have a healthy snack.",
  "Take a shower or soothing bath."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Focus your enery on work or a hobby.",
Edit line 118 - misspelled "energy"

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Make a list."
Delete lines 122, 123, 130, 131

Add - 
"Inhale as deeply as you can, and exhale slowly.",
  "Drink a cold glass of water or milk.",
  "Interact with your pet, or visit an animal shelter.",
  "Take a moment to stretch.",
  "Take stock of your immediate environment, and change one thing for the better."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Have some ice cream."
Delete line 142

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Drink water.",
Edit line 146 - "Drink a cold glass of water."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Have a cup of tea.",
Delete lines 147 and 150, edit line 149 - "Have a cup of coffee or your favorite tea."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		"Take a break for a few moments."
Delete lines 152, 153, 154, 155

Add - 
  "Did you get much sleep? Try closing your eyes for 20 minutes.",
  "Take a shower, or wash your face in cold water."

2017-07-29 22:31 UTC, kvrag commented on db/seeds.rb
> +		Action.create(content: "#{action} (#{emote})")
Delete `(#{emote})")` - we don't want to display the top emotion

2017-07-29 23:54 UTC, caristopmer approved these changes

2017-07-29 23:55 UTC, BB8bear commented on db/seeds.rb
> +		"Work out.",
Updates have been made. Please review new pull request.

2017-07-29 23:55 UTC, BB8bear commented on db/seeds.rb
> +		"Go for a run.",
Updates have been made. Please review new pull request.

2017-07-29 23:55 UTC, BB8bear commented on db/seeds.rb
> +		"Medidate.",
Updates have been made. Please review new pull request.

2017-07-30 00:06 UTC, kvrag commented on db/seeds.rb
> +		"Take a moment to be center yourself with deep breaths.Clear your mind.",
Edit to: "Take a moment to center yourself with deep breaths. Clear your mind.",

2017-07-30 00:07 UTC, kvrag commented on db/seeds.rb
> +		"Do some push-ups.",
delete line 101

2017-07-30 00:09 UTC, kvrag requested changes
Just a coupla small things!

2017-07-30 00:11 UTC, BB8bear commented on db/seeds.rb
> +		"Take a moment to be center yourself with deep breaths.Clear your mind.",
Fixed

2017-07-30 00:12 UTC, BB8bear commented on db/seeds.rb
> +		"Do some push-ups.",
Fixed

2017-07-30 00:32 UTC, kvrag approved these changes
Coo!!1

2017-07-30 00:40 UTC, merged